config/routes.rb
Rails.application.routes.draw do
  root :to => "home#outsourcing"
  get 'home/index'
  post 'home/create_challenges'
  get 'home/mitigation'
  post 'home/create_user'
  get 'home/generate_new_pdf'
  get 'mvp/new'
  post 'mvp/create'
  get 'home/outsourcing'
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/challenge.rb
class Challenge
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name,   type: String
  field :value,   type: String
  field :user_facing_text, type: String
  field :field_no, type: Integer
  field :user_id,	type: String
  field :header, type: String

  belongs_to :user, required: false
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  field :email, type: String
  field :full_name,   type: String
  field :uuid,        type: String, default: ->{ SecureRandom.hex }
  field :phone, type: String
  field :company, type: String
  field :country, type: String
  field :ext, type: String
  field :ebook, type: Boolean

  has_many :challenges

  validates :full_name, presence: true
  validates :email,:presence => true, :format => { :with => /\A[^@\s]+@[^@\s]+\z/ }

 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	session.delete(:challenges_ids) if session[:challenges_ids].present?
  end

  def outsourcing
  end

  def create_challenges
    if params[:outsourceForm].blank?
      flash[:error] = "Please select atleast one challenge area." 
      redirect_to action: :index
      return
    end
  	if !session[:challenges_ids].present?
  		challenges = challenge_param.values.flatten
  		challenges_ids = Challenge.in(name: challenges).pluck(:id).map(&:to_s)
  	end
  	session[:challenges_ids] = challenges_ids
  	redirect_to  action: :mitigation
  end 

  def mitigation
  	if session[:challenges_ids].present? 
  		@challenge_ids = session[:challenges_ids]
  	else
  		flash[:notice] = 'Please select your challenges'
  		redirect_to root_path
  	end
  end

  def create_user
    attrs =  users_params.to_h
    u = User.new
    u.full_name = attrs[:name]
    u.phone = attrs[:phone] if attrs[:phone].present?
    u.company = attrs[:company]
    u.email = attrs[:email]
    u.ext = attrs[:ext] if attrs[:ext].present?
   
    if u.save
      challenges = Challenge.in(id: attrs["challenges_id"].split(' '))
      u.challenges << challenges
      session.delete(:challenges_ids)
      RiseMailer::email_them(u).deliver_now
      chal_hash = Hash.new
      list = challenges.pluck(:header, :name)
      list.map(&:first).each {|v| chal_hash[v] = []}
      list.each {|k,v| chal_hash[k] << v }

      respond_to do |format|
        format.pdf do
          render pdf: 'evaluation',
          layout: 'layouts/pdf.html.erb',
          locals: {chal_hash: chal_hash},
          background: true,
          no_background: false,
          footer:  {   html: {   template:'shared/footer.pdf.erb'}}
      end
    end
    else
      flash[:error] = u.errors.full_messages
      redirect_to home_mitigation_path
    end
  end

  protected

  def challenge_param
  	params.require(:outsourceForm).permit!
  end

  def users_params
    params.require(:userForm).permit!
  end


end

app/controllers/mvp_controller.rb
class MvpController < ApplicationController
	layout 'mvp'
	def new
	end

	def create
		attrs = mvp_params
		u = User.new
	    u.full_name = attrs[:name]
	    u.phone = attrs[:phone] if attrs[:phone].present?
	    u.company = attrs[:company]
	    u.email = attrs[:email]
	    u.ext = attrs[:ext] if attrs[:ext].present?
	    u.country = attrs[:country] if attrs[:country].present?
	    u.ebook = true

	    if u.save
	    	send_file(Rails.root.to_s + '/public/pdf-sample.pdf', :type => 'text/html; charset=utf-8')
	    else
	    	flash[:error] = u.errors.full_messages
	    	render :new 
	    end
	end

	protected

	def mvp_params
    	params.require(:mvpForm).permit!
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pdf_handler_helper.rb
module PdfHandlerHelper
end

app/views/home/index.html.erb
  <div class="header">
    <div class="container clearfix">
      <div class="logo pull-left">
        <a href="https://www.hartleylab.com/" target='_blank' >
         <img src=<%= image_url("logo.png")%> title="Hartley Lab" alt="Hartley Lab">
        </a>
      </div>
      <h5 class="pull-right">
        <a href="https://www.hartleylab.com/" target='_blank'  title="Hartley Lab">www.hartleylab.com</a>
      </h5>
    </div>
  </div>

  <section class="outSourceForm">
    <div class="outsourceInner">     
      <div class="container">
        <h1>CHALLENGES</h1> 
        <div class="outformWrap">
          <div class="outsourceChallenges">
            <!-- <h2>
              Outsourcing challenges
            </h2> -->
            <!-- <h3>Step 1.</h3> -->
            <p>
              <span>STEP 1.</span>
              We have categorised the outsourcing challenges for you. Please tick whichever you think are applicable, so that it will help us understand your problems better.
            </p>
            <!-- <h3>Step 2.</h3> -->
            <p>
              <span>STEP 2.</span>
              Once you define your challenge areas, we will let you know how we at Hartley Lab mitigate these challenges.
            </p>
          </div>
          <% if  flash[:error].present? %>
            <div class="alert alert-danger fade in">
                <a href="#" class="close" data-dismiss="alert">&times;</a>
                <strong>Error!</strong> <%= flash[:error] %>
            </div>
          <% end %>
          <form accept-charset="UTF-8" action="create_challenges" class="outsourceForm"  name="outsourceForm" method="post">
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <div class="formSections">
              <div class="formSectionInfo">
                <i class="iconhl-communications"></i>
                <h4>Communication</h4>
              </div>
              <div class="checkbox">
                <label class="customCheckbox">
                  <input type="checkbox" name="outsourceForm[communication][]" value="Understanding">
                  <span class="customCheck"></span>
                  <span class="labelText">Understanding Gaps</span>
                </label>
              </div>
              <div class="checkbox">
                <label class="customCheckbox">
                  <input type="checkbox" name="outsourceForm[communication][]" value="Quality of deliverables">
                  <span class="customCheck"></span>
                  <span class="labelText">Quality of Deliverables</span>
                </label>
              </div>
            </div>
            <div class="formSections">
              <div class="formSectionInfo">
                <i class="iconhl-geography"></i>
                <h4>Geographical Diversities</h4>
              </div>
              <div class="checkbox">
                <label class="customCheckbox">
                  <input type="checkbox" name="outsourceForm[diversities][]" value="Time Zone">
                  <span class="customCheck"></span>
                  <span class="labelText">Time Zone</span>
                </label>
              </div>
              <div class="checkbox">
                <label class="customCheckbox">
                  <input type="checkbox" name="outsourceForm[diversities][]" value="Cultural Diversities">
                  <span class="customCheck"></span>
                  <span class="labelText">Cultural Diversity</span>
                </label>
              </div>
            </div>
            <div class="formSections">
              <div class="formSectionInfo">
                <i class="iconhl-engagement"></i>
                <h4>Engagement</h4>
              </div>
              <div class="checkbox">
                <label class="customCheckbox">
                  <input type="checkbox" name="outsourceForm[engagement][]" value="Cost Model">
                  <span class="customCheck"></span>
                  <span class="labelText">Cost Model</span>
                </label>
              </div>
              <div class="checkbox">
                <label class="customCheckbox">
                  <input type="checkbox" name="outsourceForm[engagement][]" value="Contracts">
                  <span class="customCheck"></span>
                  <span class="labelText">Contracts</span>
                </label>
              </div>
              <div class="checkbox">
                <label class="customCheckbox">
                  <input type="checkbox" name="outsourceForm[engagement][]" value="Change Management">
                  <span class="customCheck"></span>
                  <span class="labelText">Change Management</span>
                </label>
              </div>
              <div class="checkbox">
                <label class="customCheckbox">
                  <input type="checkbox" name="outsourceForm[engagement][]" value="Governance">
                  <span class="customCheck"></span>
                  <span class="labelText">Governance</span>
                </label>
              </div>
            </div>
            <div class="formSections">
              <div class="formSectionInfo">
                <i class="iconhl-process"></i>
                <h4>Project Process</h4>
              </div>
              <div class="checkbox">
                <label class="customCheckbox">
                  <input type="checkbox" name="outsourceForm[process][]" value="Project lifecycle process">
                  <span class="customCheck"></span>
                  <span class="labelText">Project Lifecycle Process</span>
                </label>
              </div>
              <div class="checkbox">
                <label class="customCheckbox">
                  <input type="checkbox" name="outsourceForm[process][]" value="Scalibility">
                  <span class="customCheck"></span>
                  <span class="labelText">Scalibility</span>
                </label>
              </div>
              <div class="checkbox">
                <label class="customCheckbox">
                  <input type="checkbox" name="outsourceForm[process][]" value="Transperancy">
                  <span class="customCheck"></span>
                  <span class="labelText">Transperancy</span>
                </label>
              </div>
            </div>
            <div class="formSections">
              <div class="formSectionInfo">
                <i class="iconhl-people"></i>
                <h4>People</h4>
              </div>
              <div class="checkbox">
                <label class="customCheckbox">
                  <input type="checkbox" name="outsourceForm[people][]" value="Retention and attrition">
                  <span class="customCheck"></span>
                  <span class="labelText">Retention and Attrition</span>
                </label>
              </div>
              <div class="checkbox">
                <label class="customCheckbox">
                  <input type="checkbox" name="outsourceForm[people][]" value="Performance">
                  <span class="customCheck"></span>
                  <span class="labelText">Performance</span>
                </label>
              </div>
            </div>
            <div class="formSections">
              <div class="formSectionInfo">
                <i class="iconhl-security"></i>
                <h4>Security &amp; IP Protection </h4>
              </div>
              <div class="checkbox">
                <label class="customCheckbox">
                  <input type="checkbox" name="outsourceForm[security][]" value="Data integrity">
                  <span class="customCheck"></span>
                  <span class="labelText">Data Integrity</span>
                </label>
              </div>
              <div class="checkbox">
                <label class="customCheckbox">
                  <input type="checkbox" name="outsourceForm[security][]" value="Data security">
                  <span class="customCheck"></span>
                  <span class="labelText">Data Security</span>
                </label>
              </div>
            </div>
            <div class="formSections">
              <div class="formSectionInfo">
                <i class="iconhl-engagement"></i>
                <h4>Technology</h4>
              </div>
              <div class="checkbox">
                <label class="customCheckbox">
                  <input type="checkbox" name="outsourceForm[technology][]" value="Knowledge Retention">
                  <span class="customCheck"></span>
                  <span class="labelText">Knowledge Retention</span>
                </label>
              </div>
              <div class="checkbox">
                <label class="customCheckbox">
                  <input type="checkbox" name="outsourceForm[technology][]" value="Training / Cross platform">
                  <span class="customCheck"></span>
                  <span class="labelText">Training / Cross Platform</span>
                </label>
              </div>
              <div class="checkbox">
                <label class="customCheckbox">
                  <input type="checkbox" name="outsourceForm[technology][]" value="Technology change management">
                  <span class="customCheck"></span>
                  <span class="labelText">Technology Change Management</span>
                </label>
              </div>
            </div>
            <button class="outsourcceSubmit" type="submit">Submit your challenges</button>
          </form>
        </div>
      </div>
    </div>
    <div class="corner">
       <img src=<%= image_url("corner.png")%> >
    </div>
  </section>
  <footer>
    <div class="container">
      <div class="clearfix">
        <ul class="clearfix list-unstyled socialLinks">
          <li>
            <a target="_blank" href="https://www.linkedin.com/company/hartley-lab" title="LinkedIn">
              <i class="icon-linkedIn"></i>
            </a>
          </li>
          <li>
            <a target="_blank" href="https://www.facebook.com/HartleyLab/" title="Facebook">
              <i class="icon-facebook"></i>
            </a>
          </li>
          <li>
            <a target="_blank" href="https://twitter.com/hartleylab" title="Twitter">
              <i class="icon-twitter"></i>
            </a>
          </li><li>
            <a target="_blank" href="https://www.instagram.com/hartley_lab/" title="Instagram">
              <i class="icon-insta"></i>
            </a>
          </li>
          <li>
            <a target="_blank" href="https://www.youtube.com/channel/UC2wvPee8Zuu_JXjfD2sdXGA" title="YouTube">
              <i class="icon-youtube"></i>
            </a>
          </li>
        </ul>
        <h6 class="copyright"> &copy; 2017 Hartley Lab. All Rights Reserved.</h6>
      </div>
    </div>
  </footer>

  <!-- video popup start -->
  <div id="videoPopup" class="videoPopup">
    <a href="javascript:void(0);" class="closePopup">&times;</a>
    <div class="videoContainer">
    </div>
  </div>

app/views/home/outsourcing.html.erb
<div id="popupBg"></div>
  <div class="header">
    <div class="container clearfix">
      <div class="logo pull-left">
        <a href="https://www.hartleylab.com/" target='_blank' >
          <img src=<%= image_url("logo.png")%> title="Hartley Lab" alt="Hartley Lab">
        </a>
      </div>
      <h5 class="pull-right">
        <a href="https://www.hartleylab.com/" target='_blank'  title="Hartley Lab" >www.hartleylab.com</a>
      </h5>
    </div>
  </div>

  <div class="outsourcingPage">
    <div class="container">
      <div class="text-center">
        <h1>OUTSOURCING</h1>
      </div>
      <div class="introContent">
        <div class="clearfix">
          <div class="introContentImg">
            <img src=<%= image_url("outsource.png")%> title="Hartley Lab" alt="Hartley Lab">
          </div>
          <div class="introContentText mainText">
            <h2>MOTIVATION BEYOND COST TO REDEFINE OUTSOURCING</h2>
            <p>Hartley delivers software outsourcing services that help you create more value for your business, improve efficiency and access new technologies and best practices.</p>
            <p>With an aim to build stronger relationships with our clients, we believe in partnerships. We believe that any project, no matter the size, is critical to your success.</p>
          </div>
          <div class="introContentText subText">
            <h4 class="conquerTitle">IT IS TIME TO GET OVER YOUR OUTSOURCING DILEMMA.</h4>
            <p>Outsourcing has its own share of challenges.</p>
            <p>Are you are thinking to outsource or have challenges in current engagement? Let's map out some of the outsourcing challenges and our approach on mitigating them.</p>
            <br>
            <a href=<%=  home_index_path %> title="Define your challenge areas">Define your challenge areas</a>
            <h5><em>A quick run through the list of challenge areas in outsourcing</em></h5>
          </div>
        </div>
      </div>

      <div class="makeItSimple frictionSimple">
        <div class="row">
          <div class="col-md-5 col-sm-6 col-sm-push-6 col-md-offset-1">
            <div class="aboutUs commonAbout">
              <h2 class="clientHeading">WHY WE'RE HERE</h2>
              <p>We are a mission-focused company driven through the passion for technology towards delivering intelligent solutions. We are a team of 50+ Engineers dedicated to solving the real world problems through technical brilliance and impeccable expertise.</p>
              <p>We not only "Make IT Smart" but we "Make IT Simple" for the people and businesses, irrespective of the scale, for them to focus on more important things, like their core business!</p>
            </div>
          </div>
          <div class="col-sm-6 col-sm-pull-6">
            <div class="videoHeading clearfix">
              <h4 class="workedHeading">OUR WORK SPEAKS VOLUMES &amp; <br> OUR CLIENTS VOUCH FOR IT</h4>
              <div class="navigateArrows">
                <!-- Left and right controls -->
                <a class="left carousel-control" href="#videoCarousel" data-slide="prev" title="Previous" alt="Previous">
                </a>
                <a class="right carousel-control" href="#videoCarousel" data-slide="next" title="Next" alt="Next">
                </a>
              </div>
            </div>  
            <div id="videoCarousel" class="commonVideoCarousel carousel slide" data-ride="carousel" data-interval="0">
              <!-- Wrapper for slides -->
              <div class="carousel-inner">
                <div class="item active">
                  <div class="videoListItem">
                    <a href="javascript:void(0);" class="videoLink videoImage" rel="5xA8ed42--Q" data-title="Member Only Hotel Rates">
                      <img src="https://i3.ytimg.com/vi/5xA8ed42--Q/maxresdefault.jpg">
                    </a>
                  </div>
                </div>
                <div class="item">
                  <div class="videoListItem">
                    <a href="javascript:void(0);" class="videoLink videoImage" rel="fsWesrmDcvQ" data-title="Member Only Hotel Rates">
                      <img src="https://i3.ytimg.com/vi/fsWesrmDcvQ/maxresdefault.jpg">
                    </a>
                  </div>
                </div>
                <div class="item">
                  <div class="testimonialWrap">
                    <p>The Hartley team has been incredible in translating business intelligence into intuitive user experiences. They've managed complex project objectives with tech savvy and have become our trusted resource in developing our satellite data platform. We've come a long way in a short time with their experienced staff who have helped with everything from early planning, design, storyboarding, and development, to testing, execution, and follow-up support. We admire their engagement, dedication, and professionalism and are excited about all the great things we will build together!</p>
                    <h5>- John Frost</h5>
                    <h5>( Head of TerraServer.com Division, PrecisionHawk )</h5>
                  </div>
                </div>
                <div class="item">
                  <div class="testimonialWrap">
                    <p>I've had the pleasure of working with Hartley Lab team for the past few months and I am very pleased with the quality of work they deliver. Hartley team is organised, and they are willing to work long hours to get the job done right.</p>
                    <h5>- Charles Kelly</h5>
                    <h5>( Director Of Software Product Management, PrecisionHawk )</h5>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>



    </div>
    <span class="corner">
      <img src=<%= image_url("corner.png")%> >
    </span>
  </div>

  <footer>
    <div class="container">
      <div class="clearfix">
        <ul class="clearfix list-unstyled socialLinks">
          <li>
            <a target="_blank" href="https://www.linkedin.com/company/hartley-lab" title="LinkedIn">
              <i class="icon-linkedIn"></i>
            </a>
          </li>
          <li>
            <a target="_blank" href="https://www.facebook.com/HartleyLab/" title="Facebook">
              <i class="icon-facebook"></i>
            </a>
          </li>
          <li>
            <a target="_blank" href="https://twitter.com/hartleylab" title="Twitter">
              <i class="icon-twitter"></i>
            </a>
          </li><li>
            <a target="_blank" href="https://www.instagram.com/hartley_lab/" title="Instagram">
              <i class="icon-insta"></i>
            </a>
          </li>
          <li>
            <a target="_blank" href="https://www.youtube.com/channel/UC2wvPee8Zuu_JXjfD2sdXGA" title="YouTube">
              <i class="icon-youtube"></i>
            </a>
          </li>
        </ul>
        <h6 class="copyright"> &copy; 2017 Hartley Lab. All Rights Reserved.</h6>
      </div>
    </div>
  </footer>

  <!-- video popup start -->
  <div id="videoPopup" class="videoPopup">
    <a href="javascript:void(0);" class="closePopup">&times;</a>
    <div class="videoContainer">
    </div>
  </div>

 
  <script type="text/javascript">
    $(document).ready(function(){


      // Video Tutorails
      //call video for event popup (video page)
      $('.videoLink').on('click', function(){

        var videoId = $(this).attr('rel');
        var title = $(this).data('title');
          $('.videoContainer').html('<div class="video-container"><iframe src="https://www.youtube.com/embed/'+ videoId +'?rel=0&autoplay=1" frameborder="0" allowfullscreen></iframe></div>');
          $('#videoPopup').fadeIn(200);
          $('#popupBg').fadeIn(300);
      });
      // close video
      $('#popupBg, .closePopup').click(function(event) {
        $('.videoContainer').empty();
        $('#popupBg, #videoPopup').fadeOut(200);
      });
      // end
    });
  </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Outsourcing Simplified!</title>
    <%= csrf_meta_tags %>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="format-detection" content="telephone=no">

    <meta name="description" content="Hire us to build you a world-class iOS, Android, or Web App. We have expert designers and developers in your city. Let's chat.">
    <meta name="keywords" content="UX AND UI Design, web engineering, Product management, Mobile Development, Website Development, DevOps, Testing & Assurance, Artificial Intelligence, IoT, Outsourcing, offshoring, nearshore">
    <meta name="author" content="Hartley Lab">


    <!-- Social Share Metas -->
    <meta property="og:title" content="Hartley Lab | Ruby on Rails, Mobile Development and Design Company in Greenville SC, Atlanta GA, Singapore, Pune India"/>
    <meta property="og:image" content="https://www.hartleylab.com/images/fb_post.jpg"/>
    <meta property="og:site_name" content="Hartley Lab"/>
    <meta property="og:description" content="Hire us to build you a world-class iOS, Android, or Web App. We have expert designers and developers in your city. Let's chat."/>
    <link rel="shortcut icon" type="image/x-icon" href=<%= image_url('favicon.ico') %> >
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all' %>
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <%= javascript_include_tag 'application' %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-63388754-3', 'auto');
      ga('send', 'pageview');

    </script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/lay_footer.pdf.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag wicked_pdf_asset_base64("pdf")  -%>
</head>
<body>
   <div class="container">
	  <h6 class="copyright"> &copy; 2017 atul Hartley Lab. All Rights Reserved.</h6>
	</div>
	<div>plain</div>
	<p>plain p</p</div>
</body>
</html>

app/views/layouts/mvp.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>MVP Essentials: Taking the Bull by its Horns &#8211; Hartley Lab</title>
    <%= csrf_meta_tags %>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="format-detection" content="telephone=no">

    
    <meta name="keywords" content="MVP, Minimum Viable Product, MVP Lab, Minimum Viable Product development company in US, India">
    <meta name="author" content="Hartley Lab">
    <meta content="The first key question in the software development process is whether your company can use a minimum valuable product. Here's how to right-size your MVP." name="description"/>

    <!-- Social Share Metas -->
    <meta property="og:title" content="Hartley Lab | Ruby on Rails, Mobile Development and Design Company in Greenville SC, Atlanta GA, Singapore, Pune India"/>
    <meta property="og:image" content="https://www.hartleylab.com/images/fb_post.jpg"/>
    <meta property="og:site_name" content="Hartley Lab"/>
    <meta property="og:description" content="Hire us to build you a world-class iOS, Android, or Web App. We have expert designers and developers in your city. Let's chat."/>

    


    <link rel="shortcut icon" type="image/x-icon" href="images/favicon.ico">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all' %>
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <%= javascript_include_tag 'application' %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-63388754-2', 'auto');
      ga('send', 'pageview');

    </script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
<title>PDF</title>
  <%= stylesheet_link_tag wicked_pdf_asset_base64("pdf")  -%>
</head>
<body>
    <%= yield %>
</body>
</html>

app/views/shared/footer.pdf.erb
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <%= javascript_include_tag "http://code.jquery.com/jquery-1.10.0.min.js" %>
    <%= javascript_include_tag "http://code.jquery.com/ui/1.10.3/jquery-ui.min.js" %>
    <%= stylesheet_link_tag wicked_pdf_asset_base64("pdf")  -%>
    <script>
      function number_pages() {
        var vars={};
        var x=document.location.search.substring(1).split('&');
        for(var i in x) {var z=x[i].split('=',2);vars[z[0]] = unescape(z[1]);}
        var x=['frompage','topage','page','webpage','section','subsection','subsubsection'];
        for(var i in x) {
          var y = document.getElementsByClassName(x[i]);
          for(var j=0; j<y.length; ++j) y[j].textContent = vars[x[i]];
        }
      }
    </script>

  </head>
 <body onload="number_pages()">
    
    <div class="header">
    <div class="container clearfix">
      <div class="logo pull-left">
        <a href="javascript:void(0);">
          <%= image_tag wicked_pdf_asset_base64("copyright-footer.png") %>
        </a>
      </div>
      <div class="pull-right">
        <span style="color: #fff; font-size: 12px; line-height: 44px;">
          Page <span class="page" ></span> of <span class="topage"></span>
        <span>
      </div>
    </div>
  </div>
  </body>

</html>